<a href="https://colab.research.google.com/github/faris-alsherif/AI-course-ITI/blob/main/Python%20Numpy%20Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [ ]:
import numpy as np
print(np.__version__)
np.show_config

2.0.2


<function numpy.__config__.show(mode='stdout')>

#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [ ]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [ ]:
arr2 = np.zeros((3,3), dtype=int)
print(arr2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [ ]:
print(arr.size)
print(arr2.itemsize)

4
8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 12 but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [ ]:
arr3 = np.zeros(12, dtype=int)
arr3[5] = 1
print(arr3)

[0 0 0 0 0 1 0 0 0 0 0 0]


#### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [ ]:
arr4 = np.arange(20,60)
print(arr4)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`

In [ ]:
print(arr4[::-1])

[59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36
 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20]


#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [ ]:
arr5 = np.arange(12,21)
print(arr5.reshape(3,3))

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

In [ ]:
arr6 = np.array([3, 7, 0, 0, 9, 0])
indices = np.nonzero(arr6)
print(indices)

(array([0, 1, 4]),)


#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [ ]:
arr7 = np.eye(4)
print(arr7)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [ ]:
arr8 = np.random.random((2,2,2))
print(arr8)

[[[0.97233474 0.94370689]
  [0.59375434 0.62175586]]

 [[0.05177443 0.92981611]
  [0.29959493 0.45327524]]]


#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [ ]:
arr9 = np.random.random((9,9))
print(arr9)
print(arr9.min())
print(arr9.max())

[[0.747411   0.42044085 0.6677546  0.31867102 0.14131944 0.19496896
  0.66161521 0.25560668 0.15094395]
 [0.18317773 0.46266179 0.44811102 0.33976508 0.13233478 0.94470675
  0.96196911 0.29645225 0.80497153]
 [0.68418054 0.44130555 0.8431291  0.67621166 0.57621095 0.49687883
  0.24582955 0.95059661 0.6381858 ]
 [0.36777742 0.47912487 0.79335875 0.14770569 0.92929829 0.26285094
  0.31935387 0.6874193  0.04106037]
 [0.92382161 0.07341862 0.05317201 0.75410405 0.42298459 0.21904273
  0.52915763 0.04256935 0.32016686]
 [0.76308069 0.98659384 0.81308002 0.68741013 0.40005464 0.40075812
  0.93284784 0.68061353 0.43244053]
 [0.25470594 0.88855548 0.97978057 0.20687254 0.54219376 0.94297809
  0.46502574 0.02733554 0.43621809]
 [0.41380149 0.798256   0.92694777 0.11545903 0.53059345 0.30277909
  0.82099151 0.92985051 0.42020759]
 [0.70713015 0.48511616 0.26660996 0.20021943 0.90667196 0.64468
  0.57457641 0.56918143 0.69020199]]
0.027335536735481947
0.986593836426928


#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [ ]:
arr10 = np.random.random(20)
print(arr10)
print(arr10.mean())

[0.61570691 0.19900689 0.72721961 0.70134583 0.57412763 0.3632936
 0.18656388 0.30252967 0.79680697 0.11623416 0.91652326 0.55739851
 0.71523366 0.78018569 0.82638348 0.48815084 0.59637483 0.41736331
 0.89161899 0.9327524 ]
0.5852410059955702


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [ ]:
arr12= np.ones((5,5), dtype=int)
arr12[1:-1,1:-1] = 0
print(arr12)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [ ]:
arr13 = np.random.random((3, 3))
padd_arr = np.pad(arr13, pad_width=1, mode='constant', constant_values=0)
print(padd_arr)

[[0.         0.         0.         0.         0.        ]
 [0.         0.08488732 0.39253131 0.40674934 0.        ]
 [0.         0.39129032 0.14363724 0.8356459  0.        ]
 [0.         0.37791007 0.73109766 0.50797252 0.        ]
 [0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [ ]:
arr14 = np.diag([1, 2, 3, 4], k=-1)
arr14 = np.zeros((6, 6), dtype=int)
arr14[np.arange(1, 5), np.arange(0, 4)] = [1, 2, 3, 4]
print(arr14)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 0 0]]


#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [ ]:
arr15 = np.zeros((6, 6), dtype=int)
arr15[::2, ::2] = 1
arr15[1::2, 1::2] = 1
print(arr15)

[[1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]]


#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [ ]:
arr16 = np.unravel_index(100, (8, 9, 10))
print(arr16)

(np.int64(1), np.int64(1), np.int64(0))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [ ]:
arr17 = np.array([[0, 1], [1, 0]])
arr18 = np.tile(arr17, (4, 4))
print(arr18)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [ ]:
arr19 = np.random.random((6, 6))
mean = np.mean(arr19)
std = np.std(arr19)
arr20 = (arr19 - mean) / std
print(arr20)

[[ 1.59345552  1.33028971 -0.25775256 -1.26786031  1.21486934 -0.94547819]
 [-0.57067925  0.42758732  0.92624425 -0.68063037  0.9445809   0.37140088]
 [ 0.11973305 -0.23680196 -0.97952324 -1.74642751  1.34072771 -1.74611326]
 [-1.77182436  1.86929716  0.10873365 -1.06936603 -0.8312829   0.27207143]
 [ 1.21369211 -0.04767236  0.92786946 -1.63998304  0.04488755  0.40462603]
 [-0.45109149 -0.11198168  0.5233006   0.05776264  1.16906517 -0.50572596]]


#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

In [ ]:
arr21 = np.array([1, 2, 3, 4, 5])
num_elem = arr21.size
elem_size = arr21.itemsize
total_bytes = num_elements * element_size
print("Number of elements:", num_elements)
print("Length of one array element in bytes:", element_size)
print("Total bytes consumed by the elements:", total_bytes)

Number of elements: 5
Length of one array element in bytes: 8
Total bytes consumed by the elements: 40


#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [ ]:
arr22 = np.random.random((6, 3))
arr23 = np.random.random((3, 4))
arr24 = np.dot(arr22, arr23)
print(arr24)

[[0.46872448 0.52530568 0.79798696 0.91589628]
 [0.63751105 1.11061765 0.83438786 1.19487296]
 [0.62588165 1.06335089 0.69630086 1.16830869]
 [0.57766306 1.5484922  0.76615926 1.03392689]
 [0.11695047 0.32271311 0.10052802 0.20527346]
 [0.29278051 0.54711046 0.57350556 0.5565717 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [ ]:
arr25 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr25[(arr25 > 3) & (arr25 < 8)] *= -1
print(arr25)

[ 1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a = np.array([1, 2])
b = np.array([4, 5])

print(a)
print(b)
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)

[1 2]
[4 5]
[False False]
[False False]
[ True  True]
[ True  True]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

a = np.array([1, 2, 3])
print(a**a)
print(a << a >> 2)
print(a < -a)
print(1j*a)
print(a/1/1)
#print(a<a>a) not work idk why

nan
0
[-9.22337204e+18]
[ 1  4 27]
[0 2 6]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]


/tmp/ipython-input-2105558604.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-2105558604.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-2105558604.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [ ]:
arr = np.array([-1.5, 2.3, -3.8, 4.1, 0.5, -0.9])
print("Original array:", arr)

rounded_arr = np.copysign(np.ceil(np.abs(arr)), arr)
print("Rounded away from zero:", rounded_arr)

rounded_arr_where = np.where(arr > 0, np.ceil(arr), np.floor(arr))
print("Rounded away from zero (using where):", rounded_arr_where)

Original array: [-1.5  2.3 -3.8  4.1  0.5 -0.9]
Rounded away from zero: [-2.  3. -4.  5.  1. -1.]
Rounded away from zero (using where): [-2.  3. -4.  5.  1. -1.]


#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [ ]:
arr27 = np.array([1, 2, 3, 4, 5])
arr28 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(arr27, arr28)
print(common_values)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`